classDiagram
    class User {
        +nom: String
        -email: String
        -motdepasse: String
        +telephone: String
        +role: String
        +avatar: String
        +bio: String
        +ride: String
        +inscription(): void
        -connexion(): void
        +creerTrajet(): void
        +rechercherTrajet(): void
        +reserverTrajet(): void
        +laisserAvis(): void

    }
